In [16]:
import torch
import torch.nn as nn
from torch.nn import functional as F
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)
block_size = 8
batch_size = 4

cuda


In [17]:
%%time
start_time = time.time()
# matrix operations here
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00007367
CPU times: total: 0 ns
Wall time: 396 μs


In [21]:

torch_rand1 = torch.rand(100,100,100,100, device=device)
torch_rand2 = torch.rand(100,100,100,100, device=device)

np_rand1 = torch_rand1.cpu().numpy()
np_rand2 = torch_rand2.cpu().numpy()

# PyTorch
start = time.time()
torch.matmul(torch_rand1, torch_rand2)
if device == "cuda":
    torch.cuda.synchronize()   # Important for accurate GPU timing
print("Torch:", time.time() - start)

# NumPy
start = time.time()
np.matmul(np_rand1, np_rand2)
print("NumPy:", time.time() - start)

Torch: 0.021526098251342773
NumPy: 0.5293242931365967


In [24]:
# Define a probability tensor
probabilities = torch.tensor([0.1, 0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the index of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 0])


In [25]:
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [26]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [27]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [28]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [29]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [30]:
input = torch.zeros(2, 3, 4)
out1 = input.transpose(0, 1)
out2 = input.transpose(-2,-1)
print(out1.shape)
print(out2.shape)

torch.Size([3, 2, 4])
torch.Size([2, 4, 3])


In [31]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

# Stack the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-0.4424,  6.2177, -5.6686], grad_fn=<SqueezeBackward4>)


In [33]:
import torch.nn.functional as F

# Create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# Apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [34]:
# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[ 0.4295, -0.0495,  0.9662,  0.7033,  0.1137,  1.2021],
        [-2.3394,  1.0070,  0.1441, -0.9067, -1.1675, -0.7363],
        [ 1.0121,  1.0453, -0.6072,  0.4395, -0.4897,  0.0477],
        [-0.8777,  0.1299, -1.3154, -1.4819, -1.2212,  1.4653]],
       grad_fn=<EmbeddingBackward0>)


In [35]:
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
# print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [36]:
int_64 = torch.randint(1, (3, 2)).float()
#type int64
float_32 = torch.rand(2,3)
#type float32
# print(int_64.dtype, float_32.dtype)
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [37]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
# print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [38]:
input = torch.rand((4, 8, 10))
B, T, C = input.shape
output = input.view(B*T, C)
print(output)
# print(input)
print(output[:, -1, :])

tensor([[0.2828, 0.4207, 0.8174, 0.6179, 0.3998, 0.6945, 0.0579, 0.3171, 0.1140,
         0.0270],
        [0.0376, 0.8565, 0.9015, 0.9864, 0.9718, 0.2691, 0.3624, 0.3625, 0.4699,
         0.3239],
        [0.3024, 0.2340, 0.3843, 0.5458, 0.8413, 0.4151, 0.7003, 0.6454, 0.6941,
         0.8620],
        [0.6660, 0.3593, 0.7404, 0.5093, 0.9108, 0.1822, 0.4135, 0.1497, 0.1650,
         0.9495],
        [0.8404, 0.0675, 0.8711, 0.8156, 0.5254, 0.9547, 0.9464, 0.1929, 0.7927,
         0.8281],
        [0.2329, 0.8506, 0.5753, 0.2024, 0.6691, 0.6527, 0.7531, 0.3639, 0.8053,
         0.7889],
        [0.8500, 0.2592, 0.5527, 0.5690, 0.8064, 0.2595, 0.1675, 0.9472, 0.6501,
         0.7737],
        [0.0905, 0.5042, 0.8576, 0.4654, 0.4304, 0.2180, 0.8177, 0.0796, 0.2959,
         0.8809],
        [0.0245, 0.3002, 0.8234, 0.5742, 0.9885, 0.6998, 0.2947, 0.0222, 0.1062,
         0.5007],
        [0.9948, 0.5458, 0.1121, 0.5359, 0.8313, 0.8435, 0.5867, 0.6554, 0.0723,
         0.2117],
        [0

IndexError: too many indices for tensor of dimension 2